version: '3.5'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.28
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    env_file: ./.env
    ports:
      - 3306:3306
    networks:
      - local
    healthcheck:
      test: "mysqladmin ping -h localhost"
      interval: 10s
      timeout: 5s
      retries: 10

  social:
    container_name: social
    restart: always
    build:
      context: ../..
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - 8080:8080
      - 6060:6060
    networks:
      - local
    depends_on:
      mysql:
        condition: service_healthy

networks:
  local:
    name: local
