version: '3.5'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.28
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    env_file: ./.env
    ports:
      - 3306:3306
    networks:
      - local
    healthcheck:
      test: "mysqladmin ping -h localhost"
      interval: 20s
      timeout: 5s
      retries: 10

  migrations:
    container_name: migrations
    image: migrate/migrate
    volumes:
      - ../../migrations:/migrations
    command:
      [ "-path", "/migrations", "-database", "mysql://social:test@tcp(mysql:3306)/social", "up" ]
    networks:
      - local
    depends_on:
      mysql:
        condition: service_healthy

  social:
    container_name: social
    restart: always
    build:
      context: ../..
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - 8080:8080
      - 6060:6060
    networks:
      - local
    depends_on:
      migrations:
        condition: service_completed_successfully

networks:
  local:
    name: local
